package br.edu.unifei.ecot12.t3.projetoFinal.leagueOfLegends;

public enum EnumAtributos {

	PENETRACAO_ARMADURA,
	DADO_ATAQUE,
	VELOCIDADE_ATAQUE,
	CHANCE_ACERTO_CRITICO,
	DANO_ACERTO_CRITICO,
	ROUBO_VIDA,
	ARMADURA,
	VIDA,
	REGENERACAO_VIDA,
	RESISTENCIA_MAGICA,
	POER_HABILIDDADE,
	REUCAO_RECARGA,
	PENETRACAO_MAGICA,
	MANA,
	VAMPIRISMO_MAGICO,
	VELOCIDADE_MOVIMENTO
	
}
